# --------------- General Settings ---------------

language: java

matrix:
  include:
    # minimum
    - dist: trusty
      jdk: openjdk6
      # workaround from https://github.com/travis-ci/travis-ci/issues/9713
      addons:
        apt:
          packages:
            - openjdk-6-jdk
      before_install:
        - jdk_switcher use openjdk6
    # LTS
    - dist: trusty
      jdk: openjdk8
    # LTS
    - dist: xenial
      jdk: openjdk11
    # latest
    - dist: xenial
      jdk: openjdk13

# --------------- Maven Cache ---------------

cache:
  directories:
    - .autoconf
    - $HOME/.m2
